config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "events#index"
  resources :users  
  resources :events

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :new_attendance_send

  belongs_to :user
  belongs_to :event

  def new_attendance_send
    UserMailer.new_attendance_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :organizer, class_name: "User"

  validates :start_date, presence: true
  validates :is_future?, presence: true
  validates :duration, presence:true
  validates :duration_is_multiple_of_5?, presence: true
  validates :title,
    presence: true,
    length: { minimum: 5, maximum: 140 }
  validates :description,
    presence: true,
    length: { minimum: 20, maximum: 1000 }
  validates :price,
    presence: true,
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  def is_future?
    self.start_date > Time.now
  end

  def duration_is_multiple_of_5?
    self.duration % 5 == 0
  end

  def end_date
    end_date = start_date + (duration * 60) 
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  has_many :attendances
  has_many :events, through: :attendances
  has_many :organized_events, foreign_key: "organizer_id", class_name: "Event"

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  end

  def show
    @my_event = Event.find(params[:id])
  end

  def create
    e = Event.new
    e.id = Event.last.id + 1
    e.title = params[:title]
    e.start_date = params[:date] # À modifier
    e.duration = params[:duration]
    e.description = params[:description]
    e.price = params[:price]
    e.location = params[:location]
    e.save
  end
end

=begin
  date_string = Date.strptime(params[:time], "%d/%m/%Y").to_s
  time_string = params[:time].to_s
  e.start_date = Time.parse("#{date_string} #{time_string}")
=end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @my_user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Voici la liste des évènements de Montpellier !!!</h1>
<div class="d-flex flex-wrap">
    <% Event.all.each do |e| %>
      <div class="card border-info mb-3" style="max-width: 20rem;">
          <div class="card-header"><%= e.location %></div>
          <div class="card-body">
              <h4 class="card-title"><%= link_to "#{e.title}", event_path(e.id) %></h4>
              <p class="card-text">
                <li><u>Début : </u><br><%= e.start_date.strftime("%d %B %Y, %H:%M") %></li>
                <li><u>Durée : </u><br><%= e.duration %> minutes</li>
                <li><u>Prix : </u><br><%= e.price %> euros</li>
                <li><u>Description : </u><br><%= e.description %></li>         
              </p>
          </div>
      </div>
  <% end %>
</div>

app/views/events/new.html.erb
<h1>Crée ton nouvel évènement !!!</h1>
<form action="/events" method="post">

  <div class="form-group">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
  </div>

  <div class="form-group">
    <label for="date">Date de début</label>
    <input type="date" class="form-control" id="date" name:"date" aria-describedby="date">
  </div>

  <div class="form-group">
    <label for="time">Heure de début</label>
    <input type="time" class="form-control" id="time" name:"time" aria-describedby="time">
  </div>
 
  <div class="form-group">
    <label for="duration">Durée</label>
    <input type="number" class="form-control" id="duration" name="duration" placeholder="Merci de rentrer la durée en minutes">
    <small id="duration" class="form-text text-muted">Multiple de 5</small>
  </div>

  <div class="form-group">
    <label for="title">Titre</label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Le nom de ton évènement">
    <small id="title" class="form-text text-muted">5 à 140 caractères</small>
  </div>

  <div class="form-group">
    <label for="description">Description</label>
    <input type="text" class="form-control" id="description" name="description" placeholder="Décris ton évènements aux autres utilisateurs">
    <small id="duration" class="form-text text-muted">20 à 1000 caractères</small>
  </div>

  <div class="form-group">
    <label for="price">Prix</label>
    <input type="number" class="form-control" id="price" name="price" placeholder="Merci de rentrer le prix en euros">
    <small id="price" class="form-text text-muted">1 à 1000 euros</small>
  </div>

  <div class="form-group">
    <label for="location">Lieu</label>
    <input type="text" class="form-control" id="location" name="location" placeholder="L'endroit où va se dérouler ton évènement">
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/events/show.html.erb
<div class="jumbotron">
  <h1 class="display-3"><%= @my_event.title %></h1>
  <p class="lead">
    <ul>
      <li><u>Nombre d'inscrits :</u> <%= @my_event.users.length %> personne(s)</li><br>
      <li><u>Email de l'organisateur :</u> <%= @my_event.organizer.email %></li><br>
      <li><u>Date et heure de début :</u> <%= @my_event.start_date.strftime("%d %B %Y, %H:%M") %></li><br>
      <li><u>Date et heure de fin :</u> <%= @my_event.end_date.strftime("%d %B %Y, %H:%M") %></li><br>
      <li><u>Lieu :</u> <%= @my_event.location %></li><br>
      <li><u>Prix :</u> <%= @my_event.price %> €</li><br>
      <li><u>Description :</u> <%= @my_event.description %></li>
    </ul>
  </p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Montpel Events</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item nav-link active">
          <%= link_to "Créer un évènement", new_event_path %>
        </li>
    </div>
    
  <div class="nav-item dropdown">
    <% if user_signed_in? %>
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Mon profil</a>
      <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 44px, 0px);">
        <% if current_user.first_name %>
          <%= link_to "#{current_user.first_name}", user_path(current_user.id) %>
        <% else %>
        <%= link_to "#{current_user.email}", user_path(current_user.id) %>
        <% end %>
        <br>
        <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
      </div>

    <% else %>
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">S'inscrire/Se connecter</a>
      <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 44px, 0px);">
        <%= link_to "S'inscrire", new_user_registration_path %>
        <br>
        <%= link_to "Se connecter", new_user_session_path %>
      </div>

    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Montpel Events</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/sketchy/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<body>
  <%= render 'layouts/header' %>
  <%= yield %>
</body>

</html>

app/views/users/show.html.erb
<% if @my_user.first_name %>
  <h1> <%= @my_user.first_name %> <%= @my_user.last_name  %></h1>
<% else %>
  <h1> <%= @my_user.email  %></h1>
<% end %>

<p>
  <ul>
    <li><u>Email : </u><%= @my_user.email %></li>
    <li><u>Description : </u><%= @my_user.description %></li>
  </ul>
</p>

<% if @my_user.first_name %>
  <h2>Voici la liste des évènements proposés par <%= @my_user.first_name %>:</h2>
<% else %>
<h2>Voici la liste des évènements proposés par <%= @my_user.email %>:</h2>
<% end %>
    <ul>
      <% @my_user.organized_events.each do |e| %>
        <li> <%= link_to "#{e.title}", event_path(e.id) %></li>
      <% end %>
    </ul>
  